### ISSUE TITLE
Add to matplotlib's list of third party tools?

### ISSUE THREAD

**Issue by anntzer** [astrofrog/mpl-scatter-density#10]
http://matplotlib.org/devdocs/thirdpartypackages/index.html
Looks worthwhile to add yourself there?

**Comment by astrofrog** [comment]
Great idea! I'll look into this shortly.

**Comment by astrofrog** [comment]
Done! http://matplotlib.org/devdocs/thirdpartypackages/index.html#mpl-scatter-density
