### ISSUE TITLE
Please do not install tests

### ISSUE THREAD

**Issue by yurivict** [astrofrog/mpl-scatter-density#25]
Production machine should have no tests installed. Tests should be run after build, and never installed.

**Comment by astrofrog** [comment]
Having the tests installed is handy to diagnose issues for users who install the package directly using ``pip`` or ``conda``. They can then easily run the tests with:

```
pytest --pyargs fast_histogram
```

Many of the projects I'm involved with choose to install tests for this reason, so I'd like to keep it this way for this package.
